name: module3_task0
on:
  push:
  schedule:
    - cron: '0 0 12 ? * 1/1 *'    
jobs:
  job1:
    steps:
      run:
        git clone Hardbass1991/holbertonschool-validation
        cd holbertonschool-validation/module3_task0
        make help
