---
name: module3_task0
on:
  push:
  schedule:
    - cron: '12 ? * 1/1 *'    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: Hardbass1991/holbertonschool-validation

      - name: cd
        run: cd holbertonschool-validation/module3_task0
      
      - name: test help command
        run: make help
