name: module3_task0
on:
  push:
  schedule:
    - cron: '0 0 12 ? * 1/1 *'    
jobs:
  job1:
    steps:
      - name: clone repository
        uses: actions/checkout@v3

      - name: test make help command
        run: 
          cd holbertonschool-validation/module3_task0
          make help
