---
name: module3_task0
on:
  push:
  schedule:
    - cron: '12 ? * 1/1 *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: actions/checkout@v3
      - name: test help command
        run: make help
